dat <- read.table("/Users/Tervs/Downloads/backpain.txt")
colnames(dat) <- c("id", 
                   "trt", 
                   "pain.rt.1", 
                   "pain.pct.1", 
                   "anx.1", 
                   "alrt.1", 
                   "time.trt.1", 
                   "pain.rt.2", 
                   "pain.pct.2", 
                   "anx.2", 
                   "alrt.2", 
                   "time.trt.2", 
                   "pain.rt.3", 
                   "pain.pct.3", 
                   "anx.3", 
                   "alrt.3", 
                   "time.trt.3", 
                   "pain.rt.4", 
                   "pain.pct.4", 
                   "anx.4", 
                   "alrt.4", 
                   "time.trt.4")
